board: OLTA PCB Laminator
name: OLTA PCB Laminator
meta: 
stepping:
  engine: RMT
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 0
  disable_delay_us: 0
  segments: 12

#Stepper Driver UART
uart1:
  txd_pin: gpio.17
  rxd_pin: gpio.16
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 115200
  mode: 8N1

kinematics:
  Cartesian:
axes:
  shared_stepper_disable_pin: NO_PIN

  x:
    steps_per_mm: 480.000000
    max_rate_mm_per_min: 100.000000
    acceleration_mm_per_sec2: 25.000000
    max_travel_mm: 32.000000
    soft_limits: false

    motor0:
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      limit_all_pin: NO_PIN
      hard_limits: false
      tmc_2209:
        uart_num: 1
        addr: 0
        r_sense_ohms: 0.110
        run_amps: 0.500
        hold_amps: 0.400
        microsteps: 16
        stallguard: 0
        stallguard_debug: false
        toff_disable: 0
        toff_stealthchop: 5
        toff_coolstep: 3
        run_mode: StealthChop
        homing_mode: StealthChop
        use_enable: true
        direction_pin: gpio.14
        step_pin: gpio.12
        disable_pin: NO_PIN
    
    motor1:
      null_motor: